EMAIL_NOT_FOUND_ERROR = "Sorry, that email was not found. Please try again."
EMAIL_EMPTY_ERROR = "Please introduce an email."
LOADING_MESSAGE_ERROR = "An error occurred while loading data. Please try again."
SAVE_CHANGES_MESSAGE_ERROR = "An error occurred while saving changes. Please try again."
ERROR_MESSAGE_RETRY = "Something went wrong, please try again."

# Messages for purchase places
INSUFFICIENT_POINTS_MESSAGE = "You do not have enough points to reserve these places."
INSUFFICIENT_PLACES_MESSAGE = "There are not enough places available for this competition."
BOOKING_COMPLETE_MESSAGE = "Great-booking complete!"
INVALID_PLACES_MESSAGE = "Invalid number of places requested."
INVALID_POINTS_MESSAGE = "Invalid points value for the club"
NON_POSITIVE_PLACES_MESSAGE = "Number of places requested must be greater than zero."
INVALID_CLUB_OR_COMPETITION = "Invalid club or competition."
MAX_PLACES_PER_BOOKING_MESSAGE = "Cannot book more than 12 places."
INVALID_DATE_FORMAT_MESSAGE = "Invalid competition date format"
PAST_COMPETITION_BOOKING_ERROR_MESSAGE = "Cannot book places for past competitions"
COMPETITION_FULL_MESSAGE = "The competition is already full. No more places available."
